#!/bin/sh
#
# A customized bspwmrc for the bspwm window manager
# https://github.com/baskerville/bspwm

# ------------------------------------------------------------------------------
#   AUTOSTART
# ------------------------------------------------------------------------------

sxhkd &  # start the simple X hotkey daemon to manage bspwm keybindings
libinput-gestures -c $XDG_CONFIG_HOME/bspwm/libinput-gestures.conf &
$XDG_CONFIG_HOME/polybar/launch.sh top bottom & # launch polybar

# ------------------------------------------------------------------------------
#   MONITORS AND WORKSPACES
# ------------------------------------------------------------------------------

bspc monitor eDP-1 -d 1 2 3 4 5 6  # my laptop built-in display

# ------------------------------------------------------------------------------
#   CONFIG
# ------------------------------------------------------------------------------

bspc config border_width                    2      # window border width
bspc config window_gap                      7      # gap that separates windows
bspc config top_padding                     30     # gap from the top frame
bspc config bottom_padding                  0      # gap form the bottom frame
bspc config left_padding                    0      # gap form the left frame
bspc config right_padding                   0      # gap from the right padding
bspc config single_monocle                  true   # single node in monocle layout (fullscreen)
bspc config click_to_focus                  true   # focus window/monitor on click (button1)
bspc config split_ratio                     0.5    # default split ratio
bspc config borderless_monocle              true   # remove borders for the monocle layout
bspc config gapless_monocle                 true   # remove gaps for the monocle layout
bspc config focus_follows_pointer           true   # focus window under the pointer
bspc config remove_disabled_monitors        true   # consider disabled monitors as disconnected
bspc config merge_overlapping_monitors      true   # merge overlapping monitors
bspc config pointer_modifier                mod4   # modifier for moving or resizing windows (super)
bspc config pointer_action1                 move   # action when button1 is pressed
bspc config pointer_action2                 resize_side    # action when button2 is pressed
bspc config pointer_action3                 resize_corner  # action when button3 is pressed

# ------------------------------------------------------------------------------
#   COLOR SCHEME
# ------------------------------------------------------------------------------

bspc config normal_border_color   "#4c566a"
bspc config active_border_color   "#1e1e1e"
bspc config focused_border_color  "#5e81ac"
bspc config presel_feedback_color "#5e81ac"

# ------------------------------------------------------------------------------
#   RULES
# ------------------------------------------------------------------------------

bspc rule -a firefox desktop=^2 follow=on
bspc rule -a TelegramDesktop desktop=^5
bspc rule -a discord desktop=^5
bspc rule -a Eclipse desktop=^3 follow=on
bspc rule -a "VirtualBox Machine" desktop=^4 follow=on
