# ZSH prompt for my main work machines
#

POWERLEVEL_MODE="nerdfont-complete"

##  LEFT PROMPT  ##

POWERLEVEL9K_PROMPT_ON_NEWLINE=true
POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(dir vcs_joined)

POWERLEVEL9K_MULTILINE_FIRST_PROMPT_PREFIX=""
POWERLEVEL9K_MULTILINE_LAST_PROMPT_PREFIX=" %F{white}\uF101%f "

POWERLEVEL9K_LEFT_SEGMENT_SEPARATOR=""
POWERLEVEL9K_LEFT_SUBSEGMENT_SEPARATOR="%F{white}\uF460"

# icons

POWERLEVEL9K_VCS_GIT_GITHUB_ICON=$'\uF408'

# colors

POWERLEVEL9K_DIR_DEFAULT_FOREGROUND="039"
POWERLEVEL9K_DIR_DEFAULT_BACKGROUND="clear"

POWERLEVEL9K_DIR_HOME_FOREGROUND="039"
POWERLEVEL9K_DIR_HOME_BACKGROUND="clear"

POWERLEVEL9K_DIR_HOME_SUBFOLDER_FOREGROUND="039"
POWERLEVEL9K_DIR_HOME_SUBFOLDER_BACKGROUND="clear"

POWERLEVEL9K_DIR_NOT_WRITABLE_FOREGROUND="214"
POWERLEVEL9K_DIR_NOT_WRITABLE_BACKGROUND="clear"

POWERLEVEL9K_DIR_ETC_FOREGROUND="039"
POWERLEVEL9K_DIR_ETC_BACKGROUND="clear"

POWERLEVEL9K_VCS_CLEAN_FOREGROUND='120'
POWERLEVEL9K_VCS_CLEAN_BACKGROUND="clear"

POWERLEVEL9K_VCS_MODIFIED_FOREGROUND='220'
POWERLEVEL9K_VCS_MODIFIED_BACKGROUND="clear"

POWERLEVEL9K_VCS_UNTRACKED_FOREGROUND='120'
POWERLEVEL9K_VCS_UNTRACKED_BACKGROUND="clear"

POWERLEVEL9K_VCS_LOADING_FOREGROUND='248'
POWERLEVEL9K_VCS_LOADING_BACKGROUND="clear"

##  RIGHT PROMPT  ##

POWERLEVEL9K_RPROMPT_ON_NEWLINE=false
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(status virtualenv go_version)

POWERLEVEL9K_RIGHT_SEGMENT_SEPARATOR=""
POWERLEVEL9K_RIGHT_SUBSEGMENT_SEPARATOR="%F{008}\uf104%F{008}"

# icons
POWERLEVEL9K_PYTHON_ICON=$'\uE235'

# colors
POWERLEVEL9K_STATUS_OK_BACKGROUND="clear"

POWERLEVEL9K_GO_VERSION_FOREGROUND="081"
POWERLEVEL9K_GO_VERSION_BACKGROUND="clear"

POWERLEVEL9K_VIRTUALENV_FOREGROUND="yellow"
POWERLEVEL9K_VIRTUALENV_BACKGROUND="clear"
