#!/bin/sh
#
# Further customization of the X session for my bspwm setup
# https://wiki.archlinux.org/index.php/Xprofile

# ------------------------------------------------------------------------------
#   ENVIRONMENT VARIABLES
# ------------------------------------------------------------------------------

export WINDOW_MANAGER=bspwm
export TERMINAL=alacritty

# ------------------------------------------------------------------------------
#   KEYBOARD
# ------------------------------------------------------------------------------

# Remap Caps Lock:
#
# - To Left Control if combined with other keys
# - To Escape if pressed no longer than 300 ms

setxkbmap -option ctrl:nocaps

[ "$(pgrep xcape | wc -l)" -gt 0 ] && killall xcape 2>/dev/null
xcape -t 300 -e 'Control_L=Escape'

# set keyboard key repeat rate
xset r rate 200 35

# Keyboard layouts (use alt + shift to toggle between layouts)
setxkbmap -layout us,us -variant ,intl -option grp:alt_shift_toggle

# ------------------------------------------------------------------------------
#   MONITORS
# ------------------------------------------------------------------------------

# set the primary display
xrandr --output 'DP-4' --primary
xrandr --output 'DP-4' --mode 2560x1440 --rate 144.00

# set the secondary monitor
xrandr --auto --output 'DP-0' --mode 1920x1080 --left-of DP-4

# ------------------------------------------------------------------------------
#   X CURSOR
# ------------------------------------------------------------------------------

# change X shaped default cursor
xsetroot -cursor_name left_ptr &

# ------------------------------------------------------------------------------
#   STARTUP PROCESSES
# ------------------------------------------------------------------------------

picom &               # start compositor
unclutter &           # hide the X mouse cursor when not needed
nitrogen --restore &  # set background image
