#!/bin/bash -ex
#
# Installation script for the broled-gen tool
# https://github.com/mattrbeam/manage/broled-gen/broled-gen.c

# compile and install the binary
gcc -W -Wall broled-gen.c -l lcms2 -o broled-gen

mkdir bin
mv broled-gen bin/broled-gen
