#!/bin/sh
#
# Further customization of the X session for my bspwm setup
# https://wiki.archlinux.org/index.php/Xprofile

# ------------------------------------------------------------------------------
#   ENVIRONMENT VARIABLES
# ------------------------------------------------------------------------------

export XINIT_EXEC=bspwm
export TERMINAL=st

# ------------------------------------------------------------------------------
#   KEYBOARD
# ------------------------------------------------------------------------------

# Remap Caps Lock:
#
# - To Left Control if combined with other keys
# - To Escape if pressed no longer than 300 ms

setxkbmap -option ctrl:nocaps

[ "$(pgrep xcape | wc -l)" -gt 0 ] && killall xcape 2>/dev/null
xcape -t 300 -e 'Control_L=Escape'

# set keyboard key repeat rate
xset r rate 200 35

# ------------------------------------------------------------------------------
#   STARTUP PROCESSES
# ------------------------------------------------------------------------------

unclutter &     # hide the X mouse cursor when not needed
