#!/bin/bash -ex
#
# Debian's root installation script for bspwm (and sxhkd)
# https://github.com/baskerville/bspwm
# https://github.com/baskerville/sxhkd

DEBIAN_FRONTEND=noninteractive sudo apt -y -q install bspwm sxhkd
