#!/bin/sh
#
# Further customization of the X session
# https://wiki.archlinux.org/index.php/Xprofile

# ------------------------------------------------------------------------------
#   XSESSION ENVIRONMENT VARIABLES
# ------------------------------------------------------------------------------

export TERMINAL=st

# ------------------------------------------------------------------------------
#   KEYBOARD
# ------------------------------------------------------------------------------

# set keyboard key repeat rate
xset r rate 300 35

# add an additional US INTL layout (alt + shift to toggle)
setxkbmap -layout us,us -variant ,intl -option grp:alt_shift_toggle

# ------------------------------------------------------------------------------
#   X CURSOR
# ------------------------------------------------------------------------------

# change X shaped default cursor
xsetroot -cursor_name left_ptr

# ------------------------------------------------------------------------------
#   STARTUP PROCESSES
# ------------------------------------------------------------------------------

picom &               # start the picom compositor
nitrogen --restore &  # set the desktop background
unclutter &           # hide the X mouse cursor when not needed
