#!/bin/bash -ex
#
# Installation script for the suckless terminal (st)
# https://st.suckless.org

# get the source code from the git repo
git clone https://git.suckless.org/st source

# copy our configuration header file
cp .dotfiles/config.h source/config.h

cd source

# download patches and apply the patches
suckless_patch="https://st.suckless.org/patches"

patches=(
    "$suckless_patch/alpha/st-alpha-0.8.2.diff"                                      # change background opacity
    "$suckless_patch/bold-is-not-bright/st-bold-is-not-bright-20190127-3be4cf1.diff" # bold doesn't apply bright color
)

for p in "${patches[@]}"; do
    curl -fSsL "$p" | patch -Np1
done

# compile and install
make clean install PREFIX="$OLDPWD"
cd ..
