#!/bin/bash -ex
#
# Installation script for the Dynamic menu (dmenu) from Suckless.org
# https://tools.suckless.org/dmenu

set -eu -o pipefail

VERSION="4.9"

# download the source
curl -fsSLO "https://dl.suckless.org/tools/dmenu-${VERSION}.tar.gz"
tar xzf "dmenu-${VERSION}.tar.gz"

cd "dmenu-${VERSION}"

# download and apply patches
patches=(
    # the version 4.9 of this patch actually removes the code required to implement
    # this functionality, will have to wait until its fixed. This patch seems to work nonetheless
    "https://tools.suckless.org/dmenu/patches/password/dmenu-password-4.7.diff"  # -P option for passwords (no echo)
)

for p in ${patches[@]}; do
    curl -fsSL "$p" | patch -Np1
done

cp ../.data/config.h config.h

make clean install PREFIX=$OLDPWD

# clean up
cd ..
rm -rf dmenu-${VERSION}*

# add the scripts to the bin directory
for script in $PWD/.data/scripts/*; do
    ln -sf "$script" "$PWD/bin/$(basename $script)"
done
