#!/bin/sh
#
# Further customization of the X session
# https://wiki.archlinux.org/index.php/Xprofile

# ------------------------------------------------------------------------------
#   XSESSION ENVIRONMENT VARIABLES
# ------------------------------------------------------------------------------

export TERMINAL=st

# ------------------------------------------------------------------------------
#   KEYBOARD
# ------------------------------------------------------------------------------

# Remap Caps Lock:
#
# - To Left Control if combined with other keys
# - To Escape if pressed no longer than 200 ms

setxkbmap -option ctrl:nocaps

[ "$(pgrep xcape | wc -l)" -gt 0 ] && killall xcape 2>/dev/null
xcape -t 200 -e 'Control_L=Escape'

# set keyboard key repeat rate
xset r rate 200 35

# ------------------------------------------------------------------------------
#   STARTUP PROCESSES
# ------------------------------------------------------------------------------

picom &               # start the picom compositor
nitrogen --restore &  # set the desktop background
unclutter &           # hide the X mouse cursor when not needed
