#!/bin/bash -ex
#
# Installation script for the terminal multiplexer TMUX
# https://github.com/tmux/tmux

set -eu -o pipefail

find_latest_tmux_release() {
    curl --silent "https://api.github.com/repos/tmux/tmux/releases/latest" \
        | grep '"tag_name"' \
        | sed -E 's/.*"([^"]+)".*/\1/'
}

VERSION=$(find_latest_tmux_release)
curl -fsSLO "https://github.com/tmux/tmux/releases/download/$VERSION/tmux-${VERSION}.tar.gz"

tar xzf "tmux-${VERSION}.tar.gz"
rm -f $_

cd "tmux-${VERSION}"

# tmux's dev team has shown some reluctance to implement the XDG specification
# for managing the configuration files. this is a simple workaround to make
# the ~/.config/tmux/tmux.conf path available for storing the configuration file
patch -Np1 -i ../.data/tmux-cfg2.diff
./configure --prefix="$OLDPWD/" CPPFLAGS="-P -DTMUX_CONF=\\\"\$(sysconfdir)/tmux.conf:~/.tmux.conf:~/.config/tmux/tmux.conf\\\""
make
make install

cd ..
rm -rf "tmux-${VERSION}"
