#!/bin/sh
#
# Startup configuration shell script for xinit/startx.
# https://wiki.archlinux.org/index.php/Xinit

# ------------------------------------------------------------------------------
#   VARIABLES WITH PATHS
# ------------------------------------------------------------------------------

# Xresources
userresources=$HOME/.config/.Xresources
sysresources=/etc/X11/xinit/.Xresources

# Xmodmap
sysmodmap=/etc/X11/xinit/.Xmodmap

# xprofile
xprofile=$HOME/.config/.xprofile

# ------------------------------------------------------------------------------
#   SETUP
# ------------------------------------------------------------------------------

# merge Xresources
[ -f "$sysresources" ] && xrdb -merge "$sysresources"
[ -f "$userresources" ] && xrdb -merge "$userresources"

[ -f "$sysmodmap" ] && xmodmap "$sysmodmap"

# add custom user font path
xset -fp $HOME/.local/share/fonts/

if [ -d /etc/X11/xinit/xinitrc.d ]; then
    for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
        [ -x "$f" ] && . "$f"
    done
    unset f
fi

# ------------------------------------------------------------------------------
#   STARTUP PROGRAMS
# ------------------------------------------------------------------------------

# souce xprofile
[ -f "$xprofile" ] && . "$xprofile"

# WINDOW_MANAGER must be set from the xprofile (this allows more configurations)
exec $WINDOW_MANAGER
